watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  stop_command: "komorebic stop --whkd"
  start_command: "komorebic start --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "None"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 26
    padding:
      top: 5
      left: 0
      bottom: -1
      right: 0
    widgets:
      left: []
      center:
        - "systray"
        - "komorebi_workspaces"
        - "whkd"
        - "cpu"
        - "memory"
        - "todo"
        - "pomodoro"
        - "clock"
        - "media"
        - "notifications"
        - "update_check"
      right: []
widgets:
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "󰮯"
      label_expanded: ""
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      container_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "<span>\ueb96</span>"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "{info[histograms][cpu_percent]}"
      update_interval: 1000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_cpu_menu"
        on_middle: "none"
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      menu:
        round_corners: true
        alignment: "center"
        direction: "down"
        offset_top: true
      icons:
        add: "\uf501   New Task" # Keep spaces for seperation
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%m/%d/%y %I:%M %p}"
      update_interval: 1000
      calendar:
        blur: true
        round_corners: false
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "none"
        on_right: "none"
        on_middle: "none"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      separator: " - "
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      scrolling_label:
        enabled: true
        update_interval_ms: 33
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
        always_scroll: false
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>󰮭</span>{count}"
      label_alt: "{count} Notification(s)"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_middle: "clear_notifications"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: true
        label: "<span></span> {count}"
        interval: 240
        exclude: []
      winget_update:
        enabled: true
        label: "<span></span> {count}"
        interval: 60
        exclude: ["Windhawk"]
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#d9c4ff" # the ring background (pale lavender)
        circle_work_progress_color: "#9effcc" # color when working (bright mint)
        circle_break_progress_color: "#a3be8c" # color when on break
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [1, 1]
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>󰧹</span>"
      special_keys:
        - key: "win"
          key_replace: "\ue70f"
        - key: "ctrl"
          key_replace: "Ctrl"
        - key: "alt"
          key_replace: "Alt"
        - key: "shift"
          key_replace: "Shift"
        - key: "left"
          key_replace: "\u2190"
        - key: "right"
          key_replace: "\u2192"
        - key: "up"
          key_replace: "\u2191"
        - key: "down"
          key_replace: "\u2193"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
