watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
        - "home"
        - "komorebi_workspaces"
        - "taskbar"
        - "media"
      center:
        - "clock"
      right:
        - "todo"
        - "pomodoro"
        - "systray"
        - "notifications"
        - "update_check"
        - "power_menu"
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span></span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~/Downloads" }
        - { title: "Documents", path: "~/Documents" }
        - { title: "Pictures", path: "~/Pictures" }
      system_menu: true
      power_menu: true
      offset_left: -6
      blur: true
      round_corners: true
      border_color: None
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: false
      controls_hide: false
      thumbnail_alpha: 40
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        play: "\ue768" # Icon for the play button in the popup.
        pause: "\ue769" # Icon for the pause button in the popup.
        prev_track: "\ue892" # Icon for the previous track button in the popup.
        next_track: "\ue893" # Icon for the next track button in the popup.
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      scrolling_label:
        enabled: true
        update_interval_ms: 33
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
        always_scroll: false
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue0ba</span>{%a, %b %d, %Y %I:%M %p}<span>\ue0bc</span>"
      callbacks:
        on_left: "none"
        on_right: "none"
        on_middle: "none"
      update_interval: 1000
      locale: ""
      timezones:
        - "America/Argentina/Buenos_Aires" # UTC−3
        - "Europe/Berlin" # UTC+1
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_left: 0
      callbacks:
        on_left: "next_timezone"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "\udb81\ude40 Tiling"
        floating_label: "\udb80\udd37 Floating"
      animation: true
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "left" # Can be "left" or "right"
      icon_size: 14 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: true
      show_volume: true
      show_network: true
      tooltip: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 14
      tooltip: false
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: false
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 240
        exclude: []
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 60
        exclude: ["Windhawk"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
